### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by markuznw** [scottoffen/grapevine#52] opened 2021-03-09 08:38 UTC
Hello and thanks for this wonderful project @scottoffen !
I started implementing in my project grapevine 4 since 5 was in rc. It was working quite fine but all my methods are async to I decided to move and try grapevine5.
I reimplemented routes as specified in the docs, added * as listening host through prefixes and all (I hope you can finish documentation because it is VERY scarce :-( ) but with grapevine5-rc7 as soon as I hit a route (for example a get route) the c# program containing the server immediately crashes with memory access violation.

`has exited with code -1073741819 (0xc0000005) 'Access violation'.`
Am I missing something? Thanks in advance!

EDIT: For what I can see the access violation crash is completely random, it happens on like 3/5 starts of the server both on get and post routes. Sometimes it is completely fine and works!

EDIT2: I found out rc6 is completely stable, so the problem must reside in some changes made in between, hope that can help ;)

**Comment by scottoffen** [comment] 2021-03-09 20:08
Can you provide a minimum set of code that exposes this behavior? Also, the OS and version of .NET you are targeting.

**Comment by markuznw** [comment] 2021-03-10 10:50
Thank you for the prompt reply Scott, sure no problem

Server init:
`            _server = RestServerBuilder.UseDefaults().Build();
            _server.Prefixes.Add($"http://*:{1234}/");
            _server.Start();`

Route:
`[RestRoute("Get","/getitem")]
        public async Task GetItem(IHttpContext context)
        {
            var ean = context.Request.QueryString["ean"];
            if (!string.IsNullOrEmpty(ean))
            {
                var item = Methods.GetItemByEan(ean).Result;
                var json = JsonConvert.SerializeObject(item, Formatting.Indented);
                await context.Response.SendResponseAsync(json);
            }
        }`

Example of returned JSON (idented for readability sake):
`{
  "id": 5478,
  "forn": "XXXX",
  "codart": "0212318",
  "Fullordercode": "23223184",
  "codint": "",
  "description": "XXXXXXXXXXXXXXXXX",
  "descecr": "XXXXXXXXXXXXXX",
  "classe": 8662,
  "iva": 22.0,
  "reparto": 0,
  "repartodesc": null,
  "peso": 150.00,
  "um": "ML",
  "trasm_flag": true,
  "print_flag": false,
  "upload_flag": true,
  "Layers": [],
  "Barcodes": [],
  "anagrafica_changed": "2018-04-23T00:00:00",
  "prezzo_changed": "2018-04-23T00:00:00",
  "costo_changed": "2018-04-23T00:00:00",
  "pz": 6,
  "imagename": null,
  "IsChanged": true,
  "Offers": [],
  "currentcost": 2.2290,
  "currentric": 39.7377,
  "currentprice": 3.8000,
  "costo": 2.2290,
  "ric": 39.7400,
  "prezzo": 3.8000,
  "offersubtotal": 1,
  "isinoffer": false,
  "MappedItem": null,
  "LastSellDateTime": "0001-01-01T00:00:00",
  "LastBoughtDateTime": "0001-01-01T00:00:00",
  "IsNew": true,
  "IsDecreased": false,
  "IsIncremented": false,
  "flags": null,
  "Status": "",
  "magazzino": true,
  "deleted": false,
  "display": ""
}`


Is it quite standard based on your examples, it was first step in using grapevine, just having a route that returns a basic JSON response for an android app that connects on local network (will try to figure out how to use authentication later on :D). To repro it, it is sufficient to open browser and point it to the server ip. It will randomly crash the server program between first and N refreshes with F5 (like said it appears to be "random"). All is fine with rc6.

App is targeting .NET Core 3.1 on Win10 X64 (2004 version)

**Comment by scottoffen** [comment] 2021-03-13 01:12
What I'm asking for here is [the minimum amount of code needed to illustrate the problem or demonstrate the behavior](https://github.com/scottoffen/grapevine/blob/main/CONTRIBUTING.md#getting-off-to-a-good-start). Your example code leaves a lot of open questions that I have to guess about, but might be part of the problem. For example:

1. Why are you adding an additional listener prefix? Does the problem only present itself when you are listening on multiple prefixes? (the default prefix added by the builder is localhost:1234).
2. 1. How are you adding the route to the router on the server? You don't include any class declaration with the `RestResource` attribute.
3. How are you generating the route? You don't include the `RestRoute` attribute on the method.
4. Do I need to create these models for `Item` and `Result`, both of which might have their own logic that you didn't include here, in order to duplicate the issue?
5. What does the static class `Methods` do? It looks like a repository of some kind, but are you hitting a database or a file or another service to get the `Item`?

Can you pair this down to a smaller example of this issue, because I am still not able to duplicate the issue.

**Comment by scottoffen** [comment] 2021-04-27 14:35
I'm closing this issue because I cannot reproduce it and the original poster has not provided any additional details.

**Closed by scottoffen** 2021-04-27 14:35 UTC
Labels: more-information-needed
